name = "after-dark"
description = "A robust, elegant dark theme"
license = "MIT"
homepage = "https://github.com/Keats/after-dark"
min_version = "0.4.0"

[extra]


[author]
name = "Vincent Prouillet"
homepage = "https://vincent.is"

[original]
author =  "comfusion"
homepage = "https://git.habd.as/comfusion/after-dark/"
repo = "https://git.habd.as/comfusion/after-dark/"
