# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{secrets.TOKEN}}
      - name: add_nojekyll
        run: |-
          git config --global user.email "ssh128@scarletmail.rutgers.edu"
          git config --global user.name "Sharif Haason"
          touch .nojekyll
          git add .
          git commit -m "auto nojekyll"
          git push -u origin gh-pages --force
